#!/bin/bash

### AUTOSTART ###
sxhkd -c ~/.config/berry/sxhkdrc &
hsetroot -fill ~/Imágenes/Wallpapers/arc_dark-wallpaper.jpg &
picom -b --config ~/.config/picom/picom.conf &
mpv --no-video ~/Música/startup--computer--short-musical-style-phrase--1-sound-effect-80767823.mp3 &
tint2 &
nm-applet &
pnmixer &
dunst -config ~/.config/dunst/dunstrc &
xscreensaver -no-splash &

# Set decoration geometry
berryc border_width       2
berryc inner_border_width 0
berryc title_height       2
berryc edge_gap           40 5 5 5

# Set decoration colors
# color-theme == arc-dark
berryc focus_color         5294e2
berryc unfocus_color       5294e2
berryc inner_focus_color   5294e2
berryc inner_unfocus_color 5294e2
berryc text_focus_color    FFFFFF
berryc text_unfocus_color  EEEEEE

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "FreeSans-9"
