#!/bin/bash

### AUTOSTART ###
sxhkd -c ~/.config/berry/sxhkdrc &
hsetroot -fill ~/Imágenes/Wallpapers/wp5728460-1080p-minimalist-wallpapers.jpg &
picom -b --config ~/.config/picom/picom.conf &
tint2 &
nm-applet &
pnmixer &
dunst -config ~/.config/dunst/dunstrc &

# Set decoration geometry
berryc border_width       2
berryc inner_border_width 0
berryc title_height       2
berryc edge_gap           30 5 5 5

# Set decoration colors
berryc focus_color         DC1624
berryc unfocus_color       DC1624
berryc inner_focus_color   DC1624	
berryc inner_unfocus_color DC1624
berryc text_focus_color    FFFFFF
berryc text_unfocus_color  EEEEEE

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "FreeSans-9"
